services:
  postgres:
    container_name: postgres-bsn
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - bsn-network
    restart: unless-stopped

  mail-dev:
    container_name: maildev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  postgres-data:
    driver: local

networks:
  bsn-network:
    driver: bridge