version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: full-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - full-postgres-volume:/var/lib/postgresql/data

volumes:
  full-postgres-volume: